# Generated by Django 4.2.6 on 2023-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convert',
            name='filePath',
        ),
        migrations.AddField(
            model_name='convert',
            name='fileName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='convert',
            name='mp3FilePath',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='convert',
            name='pdfFilePath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
